# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  hemmsenha:
    image: hemmsenha
    build:
      context: .
      dockerfile: HemmsenHA/Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NETDAEMON__APPSOURCE=sapp/apps
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ./HemmsenHA/apps:/app/apps
